massalabs/station-massa-wallet

.github/workflows/build.yml, build.sh, cmd/massa-wallet/main.go, go.mod, go.sum
1- Write a script called build.sh that will create the thyra-plugin-wallet Binary, taking in two arguments: the port number and the path to the plugin.  
2- Fix The CD calling the build.sh, and upload artifacts for multiple Operating Systems.
=> Fix CI/CD and build the compatible binary connecting wallet as plug-in to thyra

pkg/password/env.go, pkg/wallet/wallet.go
this will render:
```yaml
Version: 0
Nickname: created
Address: AU1ZbcZz9zFRj1Y2SLZJ1PW2pPeuyfHfjuQksi5MtDiAMMfyaPmV
Salt: [36, 124, 75, 123, 121, 12, 157, 70, 28, 36, 109, 250, 129, 44, 55, 227]
Nonce: [91, 156, 70, 66, 194, 97, 109, 243, 130, 106, 3, 48]
CipheredData: [197, 91, 152, 205, 97, 231, 75, 25, 158, 177, 48, 110, 255, 137, 127,
92, 141, 58, 208, 214, 240, 139, 63, 9, 172, 104, 6, 19, 55, 157, 22, 25, 255, 162,
121, 213, 97, 60, 2, 183, 32, 7, 205, 9, 28, 186, 220, 114, 84, 21, 183, 198, 50,
12, 52, 93, 141, 212, 127, 152, 242, 147, 171, 181, 160, 153, 224, 90, 67, 135,
32, 205, 21, 156, 14, 129, 187, 177, 59, 79]
PublicKey: [56, 114, 238, 179, 6, 128, 226, 11, 243, 143, 0, 172, 190, 143, 226, 241,
97, 65, 131, 243, 226, 195, 71, 226, 183, 69, 86, 235, 13, 54, 121, 32]
```
=> Improve account file format standard

pkg/plugin/constants.go, web/html/constants.js
related to https://github.com/massalabs/thyra/issues/589#issuecomment-1497312408
=> rename plugin to wallet

api/WalletPluginPostmanCollection.json, api/server/restapi/configure_massa_wallet.go, api/walletApi-V0.yml, internal/handler/wallet/api.go, internal/handler/wallet/create.go, internal/handler/wallet/create_test.go, internal/handler/wallet/delete.go, internal/handler/wallet/delete_test.go, internal/handler/wallet/export.go, internal/handler/wallet/export_test.go, internal/handler/wallet/get.go, internal/handler/wallet/get_test.go, internal/handler/wallet/import.go, internal/handler/wallet/import_test.go, internal/handler/wallet/sign.go, internal/handler/wallet/sign_test.go, pkg/wallet/wallet.go, web/html/wallet.html, web/html/wallet.js
Refactor API so that it's more restful:
pattern:
`rest/collectionName/{identifier}/actionName`
=> Refactor api

web-frontend/src/index.css
We are modifying tailwind setup.
=> modify tailwind setup

web-frontend/package-lock.json, web-frontend/package.json
We are updating dependency version for ui-kit.
=> Update react-ui-kit dependency version

web-frontend/src/main.tsx, web-frontend/src/pages/CreateAccount/StepTwo.tsx
=> added create account step 2

web-frontend/src/pages/CreateAccount/StepOne.tsx, web-frontend/src/pages/CreateAccount/StepTwo.tsx
Fix backup text from "Back-up" to "Backup"
=> Fix Backup Text in Create Account Screen 1 & 2

web-frontend/src/main.tsx, web-frontend/src/pages/CreateAccount/StepThree.tsx
=> Add Screen 3 For Account Creation

wails-frontend/index.html
We are adding the default theme class in index.html.
=> wails: add default theme class

wails-frontend/package-lock.json, wails-frontend/package.json.md5, wails-frontend/src/pages/success.tsx
=> Add Wails Success Screen

wails-frontend/src/main.tsx, wails-frontend/src/pages/failure.tsx, wails-frontend/src/utils/utils.tsx
=> Add Failure Screen Wails

wails-frontend/package.json.md5, wails-frontend/src/pages/importFile.tsx, wails-frontend/src/pages/importMethods.tsx, wails-frontend/src/pages/importPrivateKey.tsx
=> Add Wails Import User Flow

pkg/prompt/createPassword.go
We are changing the request message in the password screen.
=> wails: update password prompt req message

wails-frontend/package-lock.json, wails-frontend/src/pages/passwordPrompt.tsx
We are adding the screen to define password on wails.
=> wails : add first screen for define password

wails-frontend/src/layouts/Layout/Layout.tsx
We are adding a default layout for wails front-end screens.
=> wails: add default layout

wails-frontend/package-lock.json
We are just updating version for react-ui-kit.
=> wails: update react-ui-kit version

wails-frontend/package-lock.json, wails-frontend/src/pages/passwordPrompt.tsx, wails-frontend/src/utils/parseForm.tsx, wails-frontend/src/validation/password.tsx
We are revamp the form password logic.
=> wails: revamp form password

wails-frontend/package-lock.json
We are updating packages for react-ui-kit in wails frontend.
=> wails: update react-ui-kit packages

wails-frontend/package-lock.json, web-frontend/package-lock.json, web-frontend/src/pages/SelectAccount/SelectAccount.tsx
We are fixing components import in selectAccount page.
=> web: fix react ui-kit import

wails-frontend/package-lock.json, web-frontend/package-lock.json, web-frontend/src/custom/api/usePost.ts, web-frontend/src/i18n/en_US.json, web-frontend/src/main.tsx, web-frontend/src/pages/CreateAccount/StepOne.tsx, web-frontend/src/pages/CreateAccount/StepTwo.tsx, web-frontend/src/pages/SelectAccount/SelectAccount.tsx, web-frontend/src/pages/Welcome/Welcome.tsx, web-frontend/src/utils/parseForm.tsx
We are fixing link between steps and define password screens.
=> web: fix redirection define password

web-frontend/src/i18n/en_US.json, web-frontend/src/pages/AddAccount/AddAccount.tsx, web-frontend/src/pages/CreateAccount/StepThree.tsx
We are updating those 2 screens on web-frontend.
=> web: update step3 and add account

web-frontend/src/main.tsx, web-frontend/src/pages/Home/TransferCoins/SendCoins/SendCoins.tsx
We create directories in order to render pages. 
This is for development purposes and will be modified in the future to have unique routes
=> added directories for homepage

wails-frontend/package-lock.json, wails-frontend/package.json.md5, wails-frontend/src/pages/ImportPrivateKey/PromptNickname.tsx, wails-frontend/src/pages/backupKeyPairs.tsx, wails-frontend/src/pages/backupMethods.tsx, wails-frontend/src/pages/failure.tsx, wails-frontend/src/pages/importFile.tsx, wails-frontend/src/pages/importMethods.tsx, wails-frontend/src/pages/passwordPrompt.tsx, wails-frontend/src/pages/success.tsx
This is a refacto that use our Layout in wails, it could solve some UI bugs.
=> wails: use Layout

wails-frontend/package-lock.json, web-frontend/package-lock.json, web-frontend/src/pages/SelectAccount/SelectAccount.tsx
We are updating package for ui-kit and change `AccountSelector` component name to `Selector`.
=> web & wails: update ui-kit pack & component name

wails-frontend/src/const/stepper.ts, wails-frontend/src/i18n/en_US.json, wails-frontend/src/i18n/fr_FR.json, wails-frontend/src/pages/ImportPrivateKey/PromptNickname.tsx, wails-frontend/src/pages/ImportPrivateKey/PromptPrivateKey.tsx
We are extracting steps in one source of truth.
=> add const stepper in wails

wails-frontend/package-lock.json, web-frontend/package-lock.json, web-frontend/src/custom/api/useDelete.ts, web-frontend/src/custom/api/useResource.ts, web-frontend/src/layouts/WalletLayout/WalletLayout.tsx, web-frontend/src/pages/CreateAccount/StepThree.tsx, web-frontend/src/pages/CreateAccount/StepTwo.tsx, web-frontend/src/pages/Settings/Settings.tsx
We are adding section to `back up` or `delete account` in the `Settings` page.
=> web: add backup & delete account on settings

internal/handler/wallet/api.go, internal/handler/wallet/delete.go, pkg/app/events.go, pkg/prompt/prompt.go, wails-frontend/src/events/events.tsx, wails-frontend/src/main.tsx, wails-frontend/src/pages/confirmDelete.tsx, wails-frontend/src/pages/passwordPrompt.tsx, wails-frontend/src/utils/utils.tsx, web-frontend/src/validation/nickname.tsx
I have implemented the delete confirm, having the "wrong password error" at the end of the process because it's more complicated. So let's see if it's good enough.
=> Add confirm delete

web-frontend/src/custom/api/index.ts, web-frontend/src/custom/api/useDelete.ts, web-frontend/src/custom/api/usePost.ts, web-frontend/src/custom/api/usePut.ts, web-frontend/src/custom/api/useResource.ts, web-frontend/src/layouts/WalletLayout/WalletLayout.tsx, web-frontend/src/pages/AddAccount/AddAccount.tsx, web-frontend/src/pages/CreateAccount/StepOne.tsx, web-frontend/src/pages/CreateAccount/StepThree.tsx, web-frontend/src/pages/CreateAccount/StepTwo.tsx, web-frontend/src/pages/Home/Home.tsx, web-frontend/src/pages/SelectAccount/SelectAccount.tsx, web-frontend/src/pages/Settings/Settings.tsx, web-frontend/src/pages/Welcome/Welcome.tsx
We are fixing some padding space.
=> web: fix padding space

wails-frontend/package-lock.json, web-frontend/package-lock.json, web-frontend/src/i18n/en_US.json, web-frontend/src/layouts/WalletLayout/WalletLayout.tsx, web-frontend/src/mirage/server.ts, web-frontend/src/pages/SelectAccount/SelectAccount.tsx, web-frontend/src/pages/Settings/Settings.tsx
We are adding the "account profil" section on the `Settings` page.
=> web: implement account profil section

wails-frontend/src/i18n/en_US.json, wails-frontend/src/pages/passwordPrompt.tsx
We are updating "Sign a Transaction" screen on wails front-end.
=> wails: update sign transaction screen

api/WalletPluginPostmanCollection.json, internal/handler/wallet/api.go, internal/handler/wallet/update.go, internal/handler/wallet/update_test.go, pkg/wallet/wallet.go
during code review, you can ignore the postman collection
=> 300 implement update nickname

web-frontend/src/pages/Settings/Settings.tsx
We are adding a redirect to index when account is successfully delete.
=> web: redirect to index when delete is success

web-frontend/src/i18n/en_US.json, web-frontend/src/pages/AddAccount/AddAccount.tsx, web-frontend/src/pages/Error.tsx
We are adding text internalization on web front-end.
=> web: add text internalization

wails-frontend/package-lock.json, web-frontend/package-lock.json
We are updating packages for ui-kit.
=> web & wails: update ui-kit package

wails-frontend/src/pages/ImportPrivateKey/PromptNickname.tsx
The state was lost on the promptnickname page on linux because of the refresh so I removed it
=> fix import error

web-frontend/src/pages/TransferCoins/SendCoins/Advanced.tsx
I improved text readability + correct a little ui bug that need a div 
before div fix : 
after div fix :
=> Improve adv btn font

web-frontend/src/layouts/WalletLayout/WalletLayout.tsx
=> Add dropdown create acc redir

web-frontend/src/main.tsx, web-frontend/src/mirage/server.js, web-frontend/src/pages/Settings/SeetingsEdit.tsx, web-frontend/src/pages/Settings/SettingsOption.tsx, web-frontend/tsconfig.json
We are updating callback for button update in `Settings` page.
=> web: fix update button callback

web-frontend/src/i18n/en_US.json, web-frontend/src/layouts/Placeholder/Placeholder.tsx, web-frontend/src/main.tsx, web-frontend/src/pages/Assets/Assets.tsx, web-frontend/src/pages/Contacts/Contacts.tsx, web-frontend/src/pages/Home/Home.tsx, web-frontend/src/pages/Transactions/Transactions.tsx
=> Add placeholder screens

wails-frontend/src/pages/backupMethods.tsx
Fixed window not closing after cancelling backup.
=> wails: fix close window after cancel backup

web-frontend/src/pages/TransferCoins/SendCoins/SendConfirmation.tsx
the fees should be set as string in the body
=> fix sendcoins

web-frontend/src/layouts/WalletLayout/WalletLayout.tsx
We are fixing display screen when`WalletLayout` is used.
=> web: fix WalletLayout display

web-frontend/package-lock.json, web-frontend/src/i18n/en_US.json, web-frontend/src/pages/TransferCoins/SendCoins/Advanced.tsx, web-frontend/src/pages/TransferCoins/SendCoins/ContactList.tsx, web-frontend/src/pages/TransferCoins/SendCoins/Send.tsx, web-frontend/src/pages/TransferCoins/SendCoins/SendConfirmation.tsx, web-frontend/src/pages/TransferCoins/SendCoins/SendForm.tsx, web-frontend/src/pages/TransferCoins/SendCoins/ToolTip.tsx
UI corrections to fit design more properly
=> send coins ui correction

web-frontend/src/pages/TransferCoins/SendCoins.tsx
We are fixing `SendCoins` screen.
=> web: fix display

web-frontend/src/pages/TransferCoins/SendCoins/SendConfirmation.tsx
https://legacy.reactjs.org/docs/error-decoder.html/?invariant=301
=> Fix Send error

web-frontend/src/i18n/en_US.json, web-frontend/src/pages/TransferCoins/ReceiveCoins/CopyContent.tsx, web-frontend/src/pages/TransferCoins/ReceiveCoins/GenerateLink.tsx, web-frontend/src/pages/TransferCoins/ReceiveCoins/ReceiveCoins.tsx
=> Fix Generate Ui

web-frontend/src/pages/TransferCoins/ReceiveCoins/CopyContent.tsx, web-frontend/src/pages/TransferCoins/ReceiveCoins/GenerateLink.tsx
We remove link to share so that it only appears after being generated
=> remove default link to share

web-frontend/package-lock.json, web-frontend/src/pages/TransferCoins/SendCoins/Advanced.tsx, web-frontend/src/pages/TransferCoins/SendCoins/SendForm.tsx
minor ui fixes :+1: radio margin & balance margin
=> Fix radio padding

web-frontend/src/pages/SelectAccount/SelectAccount.tsx
We are fixing missing index value in map.
=> web: fix map index missing

web-frontend/src/components/Loading/Loading.tsx, web-frontend/src/components/index.ts, web-frontend/src/layouts/WalletLayout/WalletLayout.tsx, web-frontend/src/mirage/server.js, web-frontend/src/pages/SelectAccount/SelectAccount.tsx, web-frontend/src/pages/Welcome/Welcome.tsx
We are fixing some navigation issues and also the loading state
=> Fix home account pages

web-frontend/src/pages/Home/Home.tsx, web-frontend/src/pages/TransferCoins/ReceiveCoins/CopyContent.tsx, web-frontend/src/pages/TransferCoins/SendCoins.tsx, web-frontend/src/pages/TransferCoins/SendCoins/SendForm.tsx, web-frontend/src/utils/MassaFormating.tsx
We are adding account address section on `Home` page.
=> web: add account address section on Home

web-frontend/src/i18n/en_US.json, web-frontend/src/pages/TransferCoins/SendCoins/Advanced.tsx, web-frontend/src/pages/TransferCoins/SendCoins/Send.tsx, web-frontend/src/validation/sendInputs.tsx
=> add decimal-check-in-inputs

pkg/wallet/wallet.go, web-frontend/src/validation/nickname.tsx
We are fixing case senstive for MAC OS
=> web: fix case sensitive on mac

web-frontend/src/pages/TransferCoins/SendCoins.tsx, web-frontend/src/pages/TransferCoins/SendCoins/Advanced.tsx, web-frontend/src/pages/TransferCoins/SendCoins/Send.tsx, web-frontend/src/pages/TransferCoins/SendCoins/SendForm.tsx, web-frontend/src/validation/sendInputs.tsx
changes :
- validation of amount field when click confirm fees 
- correct button preset behaviour when opening and closing popup modal 
- correct button behaviour when choosing between custom fees and preset fees
- custom confirmation redirect to send coins screen and not confirmation screen
- validation for "1ajhjha" custom fees
=> Fix Adv Input Prb

web-frontend/src/pages/CreateAccount/StepThree.tsx, web-frontend/src/pages/CreateAccount/StepTwo.tsx, web-frontend/src/pages/TransferCoins/SendCoins/SendConfirmation.tsx
=> add use effect on navigation

web-frontend/src/mirage/server.js
We are updating some mirage endpoints
=> update mirage endpoints

web-frontend/src/main.tsx, web-frontend/src/pages/AccountSelect/AccountSelect.tsx
We are replacing SelectAccount by AccountSelect to keep the standard in routes
=> replace SelectAccount by AccountSelect

web-frontend/src/i18n/en_US.json, web-frontend/src/main.tsx, web-frontend/src/pages/AccountCreate/AccountCreate.tsx
We are replacing AddAccount by AccountCreate to keep standards in routes
=> replace AddAccount by AccountCreate

web-frontend/src/i18n/en_US.json, web-frontend/src/main.tsx, web-frontend/src/pages/TransferCoins/ReceiveCoins/GenerateLink.tsx, web-frontend/src/pages/TransferCoins/ReceiveCoins/ReceiveCoins.tsx
We are replacing receive by receive-coins to keep standards
=> replace receive by receive-coins

web-frontend/src/main.tsx, web-frontend/src/pages/Settings/SettingsUpdate.tsx
We are replacing SettingsEdit by SettingsUpdate to keep statndards
=> replace SettingsEdit by SettingsUpdate

web-frontend/src/i18n/en_US.json, web-frontend/src/pages/TransferCoins/SendCoins.tsx, web-frontend/src/pages/TransferCoins/SendCoins/Advanced.tsx, web-frontend/src/pages/TransferCoins/SendCoins/SendConfirmation.tsx, web-frontend/src/pages/TransferCoins/SendCoins/SendForm.tsx
we are replacing sendcoins to send-coins to keep standards in routes
=> replace sendcoins to send-coins

web-frontend/src/const/tabs/tabs.ts, web-frontend/src/i18n/en_US.json, web-frontend/src/layouts/WalletLayout/WalletLayout.tsx, web-frontend/src/main.tsx, web-frontend/src/pages/Home/Home.tsx, web-frontend/src/pages/TransferCoins/SendCoins/SendCoins.tsx, web-frontend/src/pages/TransferCoins/SendCoins/SendRedirect.tsx, web-frontend/src/pages/TransferCoins/TransferCoins.tsx
We are managing sending, receiving and transfer coins to be more consistent in terms of code base organization
=> manage send, receive and transfer coins

api/server/models/sign_request.go, api/server/models/sign_response.go, api/server/models/update_account_request.go, api/server/restapi/operations/massa_wallet_api.go, web-frontend/src/i18n/en_US.json, web-frontend/src/mirage/server.js, web-frontend/src/pages/Settings/SettingsUpdate.tsx, web-frontend/src/utils/index.ts, web-frontend/src/utils/parseErrors.tsx
We are fixing deletion wallet when user trying to update his nickname.
=> web: fix update nickname on settings page

web-frontend/src/pages/Settings/SettingsUpdate.tsx
We are fixing length of account profile section.
=> web: fix account profile section length

README.md
I use this VSCode extension https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint
=> fmt readme

web-frontend/package-lock.json, web-frontend/src/i18n/en_US.json, web-frontend/src/pages/TransferCoins/SendCoins/SendCoins.tsx
We are adding the toast when sending coins
=> add toast in send coins

pkg/wails/wails.go
We are removing option for resize window in wails.
=> wails: remove disable resize option

web-frontend/src/i18n/en_US.json, web-frontend/src/pages/TransferCoins/SendCoins/Advanced.tsx
[Screencast from 29-06-2023 10:49:20.webm](https://github.com/massalabs/station-massa-wallet/assets/83134981/eed65633-a7a8-466a-9d3e-5b9c73cccc0e)
=> fix : unexpected error when fees are at 0

wails-frontend/package-lock.json, web-frontend/package-lock.json
We are updating **UI-KIT** in MassaWallet.
=> wallet: update ui-kit

web-frontend/package-lock.json
update ui-kit version to enable QA testing
=> Bump Ui-Kit

internal/handler/wallet/backup.go, internal/handler/wallet/backup_test.go, wails-frontend/package-lock.json, wails-frontend/package.json.md5, wails-frontend/src/i18n/en_US.json, wails-frontend/src/pages/backupKeyPairs.tsx
=> Add Public Key to BackupKeyPairs

wails-frontend/src/pages/passwordPrompt.tsx
We are updating Sign tx screen.
=> wails: update Sign ts screen

wails-frontend/src/layouts/Layout/Layout.tsx, wails-frontend/src/pages/backupKeyPairs.tsx
fixes : https://github.com/massalabs/station-massa-wallet/issues/450#issuecomment-1620219930
=> Adjust backup screen

web-frontend/src/layouts/WalletLayout/WalletLayout.tsx, web-frontend/src/pages/Base/Base.tsx, web-frontend/src/pages/TransferCoins/SendCoins/Advanced.tsx
=> Remove Unused Exports

wails-frontend/src/pages/passwordPrompt.tsx, web-frontend/src/i18n/en_US.json, web-frontend/src/pages/TransferCoins/SendCoins/SendConfirmation.tsx
We are removing line break and useless spaces in Sign tx screen for wails and web frontend.
=> wails & web: update sign tx screen

web-frontend/src/pages/AccountSelect/AccountSelect.tsx, web-frontend/src/pages/Index/Index.tsx
We are fixing redirect after click on import a wallet.
=> web: fix redirect after import wallet

pkg/network/network.go
when I use the wallet in standalone, I still want to use the network chosen by Massa Station.
This is a technical use case that could be useful.
Current behavior:
Wallet is standalone: use buildnet
This PR introduce this behavior:
Wallet always try to fetch Massa Station network endpoint, it case of failure (Massa Station isn't running), use the buildnet.
=> standalone: use network of station if possible

web-frontend/src/mirage/factories/account.ts, web-frontend/src/mirage/handlers/account.ts, web-frontend/src/models/AccountModel.ts
=> Add mirage to assets page

wails-frontend/src/i18n/en_US.json, web-frontend/src/i18n/en_US.json
=> update error message

wails-frontend/src/i18n/en_US.json, wails-frontend/src/layouts/Layout/SignLayout.tsx, wails-frontend/src/pages/PasswordPromptHandler/ExecuteSC.tsx/ExecuteSc.tsx, wails-frontend/src/pages/PasswordPromptHandler/Sign.tsx
=> Add Execute Sc FE Screen

wails-frontend/src/i18n/en_US.json, wails-frontend/src/pages/PasswordPromptHandler/BuySellRoll/BuySellRoll.tsx, wails-frontend/src/pages/PasswordPromptHandler/ExecuteSC.tsx/ExecuteSc.tsx, wails-frontend/src/pages/PasswordPromptHandler/Sign.tsx, wails-frontend/src/pages/PasswordPromptHandler/SignSC/CallSc.tsx
=> Add Buy/Sell Roll FE

internal/handler/wallet/sign.go, wails-frontend/src/i18n/en_US.json, wails-frontend/src/pages/PasswordPromptHandler/Sign.tsx, wails-frontend/src/pages/PasswordPromptHandler/Transaction/Transaction.tsx
=> Add Transaction FE

web-frontend/src/layouts/LandingPage/LandingPage.tsx, web-frontend/src/layouts/WalletLayout/WalletLayout.tsx, web-frontend/src/mirage/factories/account.ts, web-frontend/tailwind.config.js
We are addressing this issue: https://github.com/massalabs/station-massa-wallet/issues/428
=> add back button

internal/handler/wallet/delete.go, internal/handler/wallet/sign.go, pkg/app/app.go, pkg/network/operation.go, pkg/wallet/wallet.go, wails-frontend/src/i18n/en_US.json, wails-frontend/src/pages/PasswordPromptHandler/Default.tsx, wails-frontend/src/pages/PasswordPromptHandler/Delete.tsx, wails-frontend/src/pages/PasswordPromptHandler/Sign.tsx, wails-frontend/src/pages/PasswordPromptHandler/Transfer.tsx
Add error handling on transaction and on sign
=> Add transaction error handling

web-frontend/src/pages/Index/Index.tsx
=> web: fix 0 in welcome screen

wails-frontend/src/const/operations.ts, wails-frontend/src/i18n/en_US.json, wails-frontend/src/pages/PasswordPromptHandler/BuySellRoll/BuySellRoll.tsx, wails-frontend/src/pages/PasswordPromptHandler/ExecuteSC.tsx/ExecuteSc.tsx, wails-frontend/src/pages/PasswordPromptHandler/PlainText/PlainText.tsx, wails-frontend/src/pages/PasswordPromptHandler/Sign.tsx, wails-frontend/src/pages/PasswordPromptHandler/SignSC/CallSc.tsx, wails-frontend/src/pages/PasswordPromptHandler/Transaction/Transaction.tsx, web-frontend/src/layouts/LandingPage/LandingPage.tsx
This is related to:  https://github.com/massalabs/station-massa-wallet/issues/636#issuecomment-1710620514 and https://github.com/massalabs/station-massa-wallet/issues/624#issuecomment-1710150919
We are handling two main issue in this MR:
- add amount format to be in the standard
- rework sing a message box
=> Fix sign screen

wails-frontend/src/i18n/en_US.json, wails-frontend/src/pages/PasswordPromptHandler/PlainText/PlainText.tsx
This is a fix for: https://github.com/massalabs/station-massa-wallet/issues/624#issuecomment-1713513020
=> fix sign message accordion

web-frontend/src/layouts/WalletLayout/WalletLayout.tsx
This is a fix related to: https://github.com/massalabs/station-massa-wallet/issues/692
=> fix switch account url

web-frontend/src/pages/Assets/Assets.tsx, web-frontend/src/pages/Assets/DeleteAssets/DeleteAssetModal.tsx
fixes remove asset modal ui bug with drop down menu
=> Fix Remove Asset Modal

web-frontend/src/pages/TransferCoins/TransferCoins.tsx
=> Fix Missing padding to sending page

web-frontend/src/layouts/WalletLayout/WalletLayout.tsx
Related to: https://github.com/massalabs/station-massa-wallet/pull/703#issuecomment-1719497262
=> fix switch account (local, prod, plugin)

web-frontend/src/pages/TransferCoins/SendCoins/SendConfirmation.tsx
=> Change Confirmation Screen Font Color

wails-frontend/src/pages/PasswordPromptHandler/SignSC/CallSc.tsx
=> Fix Call Sc

wails-frontend/src/i18n/en_US.json, wails-frontend/src/pages/PasswordPromptHandler/ExecuteSC.tsx/ExecuteSc.tsx, wails-frontend/src/pages/PasswordPromptHandler/PlainText/PlainText.tsx, wails-frontend/src/pages/PasswordPromptHandler/Sign.tsx, wails-frontend/src/pages/PasswordPromptHandler/SignSC/CallSc.tsx, wails-frontend/src/pages/PasswordPromptHandler/Transaction/Transaction.tsx
=> Add From Nickname to sign

wails-frontend/src/pages/backupKeyPairs.tsx, web-frontend/src/pages/Home/Home.tsx, web-frontend/src/pages/TransferCoins/ReceiveCoins/GenerateLink.tsx, web-frontend/src/pages/TransferCoins/ReceiveCoins/ReceiveCoins.tsx
fixing bug that prevents build, caused by an update on the ui-kit package
=> IMPORTANT: Update clipboard

internal/handler/wallet/sign.go, internal/handler/wallet/transfer.go, pkg/wallet/wallet.go, pkg/wallet/wallet_test.go, wails-frontend/src/pages/PasswordPromptHandler/ExecuteSC.tsx/ExecuteSc.tsx, wails-frontend/src/pages/PasswordPromptHandler/PlainText/PlainText.tsx, wails-frontend/src/pages/PasswordPromptHandler/Sign.tsx, wails-frontend/src/pages/PasswordPromptHandler/SignSC/CallSc.tsx, wails-frontend/src/pages/PasswordPromptHandler/Transaction/Transaction.tsx, wails-frontend/src/utils/massaFormat.tsx
=> 380 from address to account name in the send coins screen

documentation/wallet.adoc
- removed instructions left from work in #739
=> Removed some instructions from Non-funct section

web-frontend/cypress/e2e/acceptance/home/send.cy.tsx
this test keeps on failing, we remove un-necessary checks, and assert if elem exists instead of is visible
=> Fix Cypress CI

pkg/wallet/wallet.go
=> Clear invalid accounts on discover

wails-frontend/src/i18n/en_US.json, wails-frontend/src/i18n/i18n.ts, wails-frontend/src/pages/ImportPrivateKey/PromptNickname.tsx, web-frontend/src/i18n/en_US.json, web-frontend/src/i18n/i18n.ts, web-frontend/src/pages/TransferCoins/ReceiveCoins/GenerateLink.tsx, web-frontend/src/pages/TransferCoins/SendCoins/Advanced.tsx, web-frontend/src/utils/parseErrors.tsx
=> Various front improvements

web-frontend/package-lock.json, web-frontend/src/layouts/WalletLayout/WalletLayout.tsx
=> web: set onClickLogo

.github/workflows/build.yml
while merged, don't forget to remove the extra repo secret
=> use gihub secret of organisation

cmd/massa-wallet/massa-wallet.go, internal/handler/wallet/api.go, internal/handler/wallet/api_test.go, internal/handler/wallet/get_all_assets.go, internal/handler/wallet/sign.go, pkg/assets/asset.go, pkg/assets/asset_test.go, wails-frontend/package-lock.json, wails-frontend/package.json, wails-frontend/src/i18n/en_US.json, wails-frontend/src/pages/PasswordPromptHandler/AmountBox.tsx, wails-frontend/src/pages/PasswordPromptHandler/CallSC/CallSc.tsx, wails-frontend/src/pages/PasswordPromptHandler/CallSC/FTTransferInfo.tsx, wails-frontend/src/pages/PasswordPromptHandler/Sign.tsx, wails-frontend/src/pages/PasswordPromptHandler/SignComponentUtils/OperationCost.tsx, wails-frontend/src/pages/PasswordPromptHandler/Transaction/Transaction.tsx, wails-frontend/src/utils/parameters.ts, wails-frontend/src/utils/parseAmount.ts
first PR for the transfer FT feature
=> Wail ft transfer

.github/workflows/build.yml
The build CI fail since https://github.com/massalabs/station-massa-wallet/commit/e5b47f77b0de0b0233053d647536128a2dbd512e
=> try fix ci

web-frontend/cypress/e2e/acceptance/home/receive.cy.tsx, web-frontend/cypress/e2e/acceptance/home/send.cy.tsx, web-frontend/package.json, web-frontend/src/i18n/en_US.json, web-frontend/src/pages/TransferCoins/ReceiveCoins/GenerateLink.tsx, web-frontend/src/pages/TransferCoins/SendCoins/Advanced.tsx, web-frontend/src/pages/TransferCoins/SendCoins/AssetSelector.tsx, web-frontend/src/pages/TransferCoins/SendCoins/SendCoins.tsx, web-frontend/src/pages/TransferCoins/SendCoins/SendForm.tsx, web-frontend/src/pages/TransferCoins/TransferCoins.tsx, web-frontend/tailwind.config.js, web-frontend/vite.config.ts
thrid PR for ft transfer feature
=> FT receive link

pkg/assets/default_assets.go
For the icon : 
https://www.purrfectuniverse.com/charlie.webp
=> Purrfect Universe

internal/handler/wallet/get_all_assets_test.go, pkg/assets/default_assets.go, wails-frontend/package-lock.json, wails-frontend/src/pages/PasswordPromptHandler/BuySellRoll/BuySellRoll.tsx, wails-frontend/src/pages/PasswordPromptHandler/CallSC/FTTransferInfo.tsx, wails-frontend/src/pages/PasswordPromptHandler/ExecuteSC.tsx/ExecuteSc.tsx, wails-frontend/src/pages/PasswordPromptHandler/SignComponentUtils/OperationCost.tsx, wails-frontend/src/pages/PasswordPromptHandler/Transaction/Transaction.tsx, web-frontend/cypress/e2e/acceptance/home/send.cy.tsx, web-frontend/package-lock.json, web-frontend/src/pages/AccountSelect/AccountSelect.tsx, web-frontend/src/pages/Home/Home.tsx, web-frontend/src/pages/TransferCoins/ReceiveCoins/GenerateLink.tsx, web-frontend/src/pages/TransferCoins/SendCoins/AssetSelector.tsx, web-frontend/src/pages/TransferCoins/SendCoins/ContactList.tsx, web-frontend/src/pages/TransferCoins/SendCoins/SendConfirmation.tsx, web-frontend/src/pages/TransferCoins/SendCoins/SendForm.tsx, web-frontend/src/utils/math.ts
=> BSC tokens and update ui kit format amount

internal/handler/wallet/nodeFetcherMock_test.go, internal/handler/wallet/prompterMock_test.go, pkg/app/app.go, pkg/wallet/filesystem.go
fix some function names in comment
=> chore: fix some function names in comment
